name: Release

on:
  workflow_dispatch:
    inputs:
      GPG_PRIVATE_KEY:
        description: 'The private key to sign the artifacts'
        required: true
        type: string
      GPG_PASSPHRASE:
        description: 'The passphrase for the private key'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-jdk
      - uses: ./.github/actions/setup-maven-cache
      - uses: ./.github/actions/run-tests

      - name: Prepare for release
        run: ./mvnw versions:set -DremoveSnapshot=true

      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)

      - name: Import GPG key
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Deploy
        run: ./mvnw -Psign --batch-mode -DskipTests deploy
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/workflows/changelog-configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.output.version }}
          release_name: Release ${{ steps.get_version.output.version }}
          draft: false
          prerelease: false
          body: ${{steps.build_changelog.outputs.changelog}}

      - name: Upload all jars to Release
        run: |
          for file in ./target/*.jar; do
            echo "Uploading $file"
            curl \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: $(file -b --mime-type $file)" \
              --data-binary @"$file" \
              "${{ steps.create_release.outputs.upload_url }}?name=$(basename $file)"
          done
        shell: bash

      - name: Commit release POM and Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Release ${{ steps.get_version.outputs.version }}" -a
          git tag ${{ steps.get_version.outputs.version }}

      - name: Set next development version
        run: ./mvnw versions:set -DnextSnapshot=true

      - name: Commit next snapshot
        run: |
          git commit -m "Next development version" -a

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
